version: '3.1'

services:
  mongodb:
    image: mongo:5.0.15
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=htran
    ports:
      - 27019:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

    # docker compose -p mongodb-4rn up -d
